### ISSUE TITLE
ascii decoding issue with Py < 3.9

### ISSUE THREAD

**Issue by kaushik-work** [rabix/benten#109]
For certain CWL files, e.g. `tests/cwl/ebi/workflows/cmsearch-multimodel-wf.cwl` when the code is installed in Python < 3.9 we obtain the following error:

```
ERROR:benten.langserver.server:Unexpected error: 'ascii' codec can't decode byte 0xe2 in position 460: ordinal not in range(128)
Traceback (most recent call last):
  File "benten/langserver/server.py", line 65, in run
    self.handle(request)
  File "benten/langserver/server.py", line 95, in handle
    response = to_dict(self._dispatch(client_query))
  File "benten/langserver/server.py", line 145, in _dispatch
    return f(client_query)
  File "benten/langserver/fileoperation.py", line 56, in serve_textDocument_didOpen
    document = Document(
  File "benten/code/document.py", line 38, in __init__
    self.update(text)
  File "benten/code/document.py", line 57, in update
    self.parse(cwl)
  File "benten/code/document.py", line 89, in parse
    inferred_type.parse(
  File "benten/cwl/recordtype.py", line 167, in parse
    inferred_type.parse(
  File "benten/cwl/lomtype.py", line 104, in parse
    inferred_type.parse(
  File "benten/cwl/recordtype.py", line 167, in parse
    inferred_type.parse(
  File "benten/cwl/linkedfiletype.py", line 38, in parse
    validate_and_load_linked_file(doc_uri, self.prefix, value_range, problems)
  File "benten/cwl/lib.py", line 153, in validate_and_load_linked_file
    contents = linked_file.open("r").read()
  File "/Users/runner/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 460: ordinal not in range(128)
```

**Comment by ghost** [comment]
Use Py 3.9 for server packaging.

**Comment by tetron** [comment]
Are you sure the solution isn't for `benten/cwl/lib.py` to explicitly open the file with UTF-8 encoding?

**Comment by tetron** [comment]
FWIW the main reason for the binary packages to use Python 3.8 was that there wasn't a precompiled dukpy module for Python 3.9.  Maybe that's changed.
